// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7zLL3YoDX_LNCSAE2LF-A0YznlMclhJg',
    appId: '1:138766808401:web:ac3e0158301843103a8f70',
    messagingSenderId: '138766808401',
    projectId: 'webfarming-delivery',
    authDomain: 'webfarming-delivery.firebaseapp.com',
    storageBucket: 'webfarming-delivery.firebasestorage.app',
    measurementId: 'G-XWYWPL0FTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpeLbh0P_x3Rh1NySvTEGNpZrH29GdK6I',
    appId: '1:138766808401:android:00877075d76827cc3a8f70',
    messagingSenderId: '138766808401',
    projectId: 'webfarming-delivery',
    storageBucket: 'webfarming-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnoLBf_6xf_cVM-gUv3kUrXwcXRRr1TlE',
    appId: '1:138766808401:ios:7bc5b5ddb77b9f833a8f70',
    messagingSenderId: '138766808401',
    projectId: 'webfarming-delivery',
    storageBucket: 'webfarming-delivery.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnoLBf_6xf_cVM-gUv3kUrXwcXRRr1TlE',
    appId: '1:138766808401:ios:7bc5b5ddb77b9f833a8f70',
    messagingSenderId: '138766808401',
    projectId: 'webfarming-delivery',
    storageBucket: 'webfarming-delivery.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIGZW_eBm2qeiW41kwOMOmhZCSQalDX4s',
    appId: '1:138766808401:web:4b71c4a53eec40683a8f70',
    messagingSenderId: '138766808401',
    projectId: 'webfarming-delivery',
    authDomain: 'webfarming-delivery.firebaseapp.com',
    storageBucket: 'webfarming-delivery.firebasestorage.app',
    measurementId: 'G-403DGMGZK4',
  );
}
